### ISSUE TITLE
must ‘pkcs12_filename’ be set to a full path?

### ISSUE THREAD

**Issue by boziyoung** [m-click/requests_pkcs12#24]
`    

- def __init__(self, url, method, payload=None, json=None, parameter=None, header=None):
-         """ set some parameters about the request"""
-         self.url = url
-         self.method = method
-         self.parameter = parameter
-         self.payload = payload
-         self.json = json
-         self.header = header
-         self.pkcs12_filename = "./cert/arpdyqrqay.p12"
-         self.pkcs12_password = '123'

`
fault:
Traceback (most recent call last):
  File "/Users/zz/PycharmProjects/SDP-test/test1.py", line 31, in <module>
    ApiTest.sign_up("boziyoung@a.a", 'young', 'QQqq11!!')
  File "/Users/zz/PycharmProjects/SDP-test/API/api_summary.py", line 70, in sign_up
    sign_result = sign.send_method()
  File "/Users/zz/PycharmProjects/SDP-test/API/send_method.py", line 31, in send_method
    response = requests_pkcs12.request(method=self.method, url=self.url, data=self.payload, json=self.json,
  File "/Users/zz/PycharmProjects/SDP-test/venv/lib/python3.8/site-packages/requests_pkcs12.py", line 121, in request
    pkcs12_adapter = Pkcs12Adapter(
  File "/Users/zz/PycharmProjects/SDP-test/venv/lib/python3.8/site-packages/requests_pkcs12.py", line 93, in __init__
    with open(pkcs12_filename, 'rb') as pkcs12_file:
FileNotFoundError: [Errno 2] No such file or directory: './cert/arpdyqrqay.p12'

**Comment by vog** [comment]
No, a relative path should be just fine.

I assume that you either have a typo in the filename, or something in your code that changes the current directory, or that your program is not started in the needed directory.

**Comment by vog** [comment]
As there was to response for several months, I assume this issue has been solved in the meantime.

@boziyoung Feel free to open a new ticket if you encounter further issues.
